name: mock
on:
  schedule:
#    - cron: '0 */3 * * *'
    
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: run script
        shell: cmd
        continue-on-error: false
        timeout-minutes: 10
        run: |
          cd .\src
          RUN.bat
          if not %errorlevel%==0 exit 110
          
      - name: commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add --all
          git commit -m  "Last Update at $(date +"%Y-%m-%d %H:%M")"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
